#!/usr/bin/env python3
"""Regenerate stealth/patches/ from the current working tree.

For every path in stealth/OWNED_FILES, write a unified diff of
(UPSTREAM_BASE commit -> working tree) into patches/<sanitized>.patch, and
rewrite patches/series in OWNED_FILES order.

Run this after editing any upstream file so the patch set stays the source of
truth for "what we changed in upstream". Net-new files under stealth/ are NOT
patched — they're just committed normally.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _lib import (  # noqa: E402
    PATCHES_DIR, SERIES_FILE, base_commit, git, owned_files, patch_name,
)


def main():
    os.makedirs(PATCHES_DIR, exist_ok=True)
    base = base_commit()
    files = owned_files()
    series = []
    stale = {f for f in os.listdir(PATCHES_DIR) if f.endswith(".patch")}

    for path in files:
        # Diff base..worktree for just this file. Empty diff => file unchanged.
        res = git("diff", base, "--", path, check=False)
        if res.returncode != 0:
            print(f"  warn: git diff failed for {path}: {res.stderr.strip()}")
            continue
        diff = res.stdout
        name = patch_name(path)
        out = os.path.join(PATCHES_DIR, name)
        if not diff.strip():
            print(f"  skip (no changes): {path}")
            if os.path.exists(out):
                os.remove(out)
            stale.discard(name)
            continue
        with open(out, "w") as f:
            f.write(diff)
        series.append(name)
        stale.discard(name)
        print(f"  wrote: patches/{name}")

    # Remove patches for files no longer owned.
    for orphan in sorted(stale):
        os.remove(os.path.join(PATCHES_DIR, orphan))
        print(f"  removed orphan: patches/{orphan}")

    with open(SERIES_FILE, "w") as f:
        f.write("# Auto-generated by refresh_patches.py — apply order.\n")
        for name in series:
            f.write(name + "\n")
    print(f"done: {len(series)} patch(es), base {base[:12]}")


if __name__ == "__main__":
    main()
